### ISSUE TITLE
full CSS is escaped if a style definition seems invalid

### ISSUE THREAD

**Issue by optyler** [nahsra/antisamy#117]
Hi guys. 

I don't know if this is a bug or just a lack of knowledge about the options... so, sorry if i'm in the wrong place. 

I'm writing for my company a newsletter template that is filled with documents and render on an admin webpage. Administrators can then edit the pre-rendered newsletter and edit it, if they want, in a richtext box,  before sending to the customers. So, when they save their changes, we `POST` the full modified html, check it with antisamy, and save it in DB.

If you ever worked to produce newsletters, you know we have to put tons of css for each kind of mail clients, use specific vendor prefixes, all sort of media queries and so on...

Here is the content of a `style` tag inserted in the `head` of my document.

```css
<style type="text/css">
.ReadMsgBody {
  width: 100%;
}
p {
  margin: 10px 0;
  padding: 0px;
}
table {
  border-collapse: collapse;
}
p, a, li, td, blockquote {
   mso-line-height-rule: exactly; /* PAY ATTENTION TO THIS LINE*/
}
h1 {
color: #2C445A;
font-family: Verdana, Geneva, sans-serif;
font-size: 15px;
font-style: normal;
font-weight: bold;
line-height: 150%;
letter-spacing: normal;
text-align: center;
}
h2 {
font-family: Verdana, Geneva, sans-serif;
color: #fff;
font-size: 15px;
font-weight: bold;
}
[...] and much more
```

After validation, the CSS was truncated after the first "non standard" property.
Here is the result : 
```css
<style type="text/css">
*.ReadMsgBody {
	width: 100.0%;
}
p {
	margin: 10.0px 0;
	padding: 0.0px;
}
table {
	border-collapse: collapse;
}
p, a, li, td, blockquote {
}
	</style>
```

All the content after `mso-line-height-rule: exactly;` has disappeared.

Here are my questions : 
- is this a bug ? 
- is there an option to "allow vendor prefixes" ? 
- is there an option to "continue the validation if a property is invalide" ?
- is there a way to validate media queries ? ( `@media only screen and (max-width: 480px) {` )

Thanks
